spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizb3
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
server:
  port: 8080
