version: '3.8'
services:
  db:
    image: postgres:15
    container_name: museum-db
    restart: always
    environment:
      POSTGRES_USER: museum
      POSTGRES_PASSWORD: museum123
      POSTGRES_DB: museum_b3
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: museum-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/museum_b3
      SPRING_DATASOURCE_USERNAME: museum
      SPRING_DATASOURCE_PASSWORD: museum123
    ports:
      - "8080:8080"

volumes:
  db_data:
